# Generated by Django 3.1.7 on 2021-04-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Entity name', max_length=255, unique=True)),
                ('description', models.CharField(blank=True, help_text='Human-readable description', max_length=255, null=True)),
                ('plural', models.CharField(blank=True, help_text='Human-readable plural name', max_length=255, null=True)),
                ('documentation', models.TextField(blank=True, help_text='Documentation', null=True)),
                ('is_person', models.BooleanField(default=False, help_text='Specifies whether the entity is a single entity (`Person`) or a group entity')),
            ],
        ),
    ]
