# Generated by Django 3.1.7 on 2021-05-17 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('variables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.TextField(help_text='Description of the energy saving activity')),
                ('version_name', models.TextField(help_text='Rule Draft Version of this activity')),
                ('version_code', models.CharField(help_text='Abbreviation of the drafted Rules Version Name', max_length=255)),
                ('sub_method', models.TextField(help_text='Description of the SubMethod')),
                ('eligibility', models.ManyToManyField(blank=True, help_text='eligibility requirements for this activity.', related_name='eligibility', to='variables.Variable')),
                ('energy_savings', models.ForeignKey(blank=True, help_text='The Final output variable that gives the energy savings of this activity.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='energy_savings_var', to='variables.variable')),
                ('equipment', models.ManyToManyField(blank=True, help_text='equipment requirements for this activity.', related_name='equipment', to='variables.Variable')),
                ('implementation', models.ManyToManyField(blank=True, help_text='implemention requirements for this activity.', related_name='implementation', to='variables.Variable')),
            ],
        ),
    ]
