# Generated by Django 3.1.7 on 2021-04-26 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Variable name', max_length=255)),
                ('directory', models.TextField(help_text='File directory of this variable')),
                ('description', models.TextField(blank=True, help_text='Human-readable description', null=True)),
                ('value_type', models.CharField(blank=True, choices=[('Int', 'Int'), ('Float', 'Float'), ('Boolean', 'Boolean'), ('String', 'String'), ('Date', 'Date'), ('Enum', 'Enum')], help_text='The value type of the variable', max_length=16, null=True)),
                ('definition_period', models.CharField(blank=True, choices=[('MONTH', 'MONTH'), ('YEAR', 'YEAR'), ('ETERNITY', 'ETERNITY')], help_text='Period the variable is defined for', max_length=16, null=True)),
                ('reference', models.TextField(blank=True, help_text='Legislative reference describing the variable', null=True)),
                ('default_value', models.CharField(blank=True, help_text='Default value of the variable.', max_length=255, null=True)),
                ('possible_values', models.JSONField(blank=True, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('children', models.ManyToManyField(blank=True, related_name='parent_set', to='variables.Variable')),
                ('entity', models.ForeignKey(blank=True, help_text='Entity the variable is defined for', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variables', to='entities.entity')),
                ('parents', models.ManyToManyField(blank=True, related_name='children_set', to='variables.Variable')),
            ],
        ),
    ]
